#
#	Configuration part
#

PRJNAME=butler-qt

DEVEL_VERSION_MAJOR=0
DEVEL_VERSION_MINOR=3
DEVEL_VERSION_PATCH=0

RELEASE_VERSION_MAJOR=0
RELEASE_VERSION_MINOR=3
RELEASE_VERSION_PATCH=0

CSJP_PKGNAME=csjp-00.3
DATAMODEL_PKGNAME=butler-datamodel-00.3
SQL_PKGNAME=butler-sqlite-00.3

PRJDESC=Butler is a shopping list like basic home economy helper tool.
DEVELOPMENT_START_YEAR=2009

AUTHOR=Peter Csaszar
EMAIL=csjpeter@gmail.com

CONFIG=debug,stlcompatible

include make/definitions.minc

COMPILETIME_LIB_DEPS+=sqlite3
GENTOO_RUNTIME_DEPS+=>=dev-db/sqlite-3.6.0
DEBIAN_RUNTIME_DEPS+=, sqlite3 (>=3.6.0)

COMPILETIME_LIB_DEPS+=$(DATAMODEL_PKGNAME)
GENTOO_COMPILETIME_DEPS+=dev-libs/$(DATAMODEL_PKGNAME)
DEBIAN_COMPILETIME_DEPS+=, $(DATAMODEL_PKGNAME)
CFLAGS+=$(shell pkg-config --cflags $(DATAMODEL_PKGNAME))
STATICS+=$(shell pkg-config --static --libs $(DATAMODEL_PKGNAME))
#LIBS+=$(shell pkg-config --libs $(DATAMODEL_PKGNAME))
GENTOO_RUNTIME_DEPS+=dev-libs/$(DATAMODEL_PKGNAME)
DEBIAN_RUNTIME_DEPS+=, $(DATAMODEL_PKGNAME)

COMPILETIME_LIB_DEPS+=$(SQL_PKGNAME)
GENTOO_COMPILETIME_DEPS+=dev-libs/$(SQL_PKGNAME)
DEBIAN_COMPILETIME_DEPS+=, $(SQL_PKGNAME)
CFLAGS+=$(shell pkg-config --cflags $(SQL_PKGNAME))
STATICS+=$(shell pkg-config --static --libs $(SQL_PKGNAME))
#LIBS+=$(shell pkg-config --libs $(SQL_PKGNAME))
GENTOO_RUNTIME_DEPS+=dev-libs/$(SQL_PKGNAME)
DEBIAN_RUNTIME_DEPS+=, $(SQL_PKGNAME)

COMPILETIME_LIB_DEPS+=csjp$(CSJP_PKGNAME)
GENTOO_COMPILETIME_DEPS+=dev-libs/$(CSJP_PKGNAME)
DEBIAN_COMPILETIME_DEPS+=, $(CSJP_PKGNAME)
CFLAGS+=$(shell pkg-config --cflags $(CSJP_PKGNAME))
STATICS+=$(shell pkg-config --static --libs $(CSJP_PKGNAME))
#LIBS+=$(shell pkg-config --libs $(CSJP_PKGNAME))
GENTOO_RUNTIME_DEPS+=dev-libs/$(CSJP_PKGNAME)
DEBIAN_RUNTIME_DEPS+=, $(CSJP_PKGNAME)

COMPILETIME_LIB_DEPS+=QtCore
GENTOO_COMPILETIME_DEPS+=>=x11-libs/qt-core-4.4.0
DEBIAN_COMPILETIME_DEPS+=, libqt4-core (>=0.4.4)
CFLAGS+=$(shell pkg-config --cflags QtCore)
STATICS+=$(shell pkg-config --static --libs QtCore)
#LIBS+=$(shell pkg-config --libs QtCore)
GENTOO_RUNTIME_DEPS+=>=x11-libs/qt-core-4.4.0
DEBIAN_RUNTIME_DEPS+=, libqt4-core (>=4.4.0)

COMPILETIME_LIB_DEPS+=QtSql
GENTOO_COMPILETIME_DEPS+=>=x11-libs/qt-sql-4.4.0
DEBIAN_COMPILETIME_DEPS+=, libqt4-sql (>=0.4.4)
CFLAGS+=$(shell pkg-config --cflags QtSql)
STATICS+=$(shell pkg-config --static --libs QtSql)
#LIBS+=$(shell pkg-config --libs QtSql)
GENTOO_RUNTIME_DEPS+=>=x11-libs/qt-sql-4.4.0
DEBIAN_RUNTIME_DEPS+=, libqt4-sql (>=4.4.0)

COMPILETIME_LIB_DEPS+=QtGui
GENTOO_COMPILETIME_DEPS+=>=x11-libs/qt-gui-4.4.0
CFLAGS+=$(shell pkg-config --cflags QtGui)
STATICS+=$(shell pkg-config --static --libs QtGui)
#LIBS+=$(shell pkg-config --libs QtGui)
GENTOO_RUNTIME_DEPS+=>=x11-libs/qt-gui-4.4.0

INCLUDES=-I src

DEFINES+=-DICONS_PATH=\"/$(PREFIX)/share/$(PKGNAME)/icons/\"
DEFINES+=-DQT_NO_CAST_TO_ASCII

#CFLAGS += -finstrument-functions-exclude-file-list=csjp_btree.h,csjp_ownerbtree.h,csjp_container.h,csjp_reference_container.h,csjp_owner_container.h,csjp_sorter_reference_container.h,csjp_sorter_owner_container.h
#CFLAGS += -finstrument-functions-exclude-function-list=headerData,rowCount,columnCount,Model::data,Model::index,tr,queryAt,index,has

#armel check: cpp -dM /dev/null | grep __ARMEL__

BIN_DESKTOP=$(PREFIX)/bin/$(PKGNAME)

HEADERDIR=$(P_HOST)/$(PKGNAME)-dev/$(TCROOT)/$(PREFIX)/include/$(PKGNAME)

-include $(DESKTOP_OBJECTS:.o=.d)

DESKTOP_OBJECTS= \
	$(P_HOST)/$(WORK)/src/butler_accountingview.o \
	$(P_HOST)/$(WORK)/src/butler_application.o \
	$(P_HOST)/$(WORK)/src/butler_buyitemview.o \
	$(P_HOST)/$(WORK)/src/butler_config.o \
	$(P_HOST)/$(WORK)/src/butler_custommodel.o \
	$(P_HOST)/$(WORK)/src/butler_customview.o \
	$(P_HOST)/$(WORK)/src/butler_edititemview.o \
	$(P_HOST)/$(WORK)/src/butler_editshopview.o \
	$(P_HOST)/$(WORK)/src/butler_edittagview.o \
	$(P_HOST)/$(WORK)/src/butler_editwareview.o \
	$(P_HOST)/$(WORK)/src/butler_itemsmodel.o \
	$(P_HOST)/$(WORK)/src/butler_localdb.o \
	$(P_HOST)/$(WORK)/src/butler_mainview.o \
	$(P_HOST)/$(WORK)/src/butler_newitemview.o \
	$(P_HOST)/$(WORK)/src/butler_newshopview.o \
	$(P_HOST)/$(WORK)/src/butler_newtagview.o \
	$(P_HOST)/$(WORK)/src/butler_newwareview.o \
	$(P_HOST)/$(WORK)/src/butler_queryoptionsview.o \
	$(P_HOST)/$(WORK)/src/butler_shoppingmodel.o \
	$(P_HOST)/$(WORK)/src/butler_shoppingview.o \
	$(P_HOST)/$(WORK)/src/butler_shopsmodel.o \
	$(P_HOST)/$(WORK)/src/butler_shopsview.o \
	$(P_HOST)/$(WORK)/src/butler_stockmodel.o \
	$(P_HOST)/$(WORK)/src/butler_stockview.o \
	$(P_HOST)/$(WORK)/src/butler_tagfilterview.o \
	$(P_HOST)/$(WORK)/src/butler_tagsmodel.o \
	$(P_HOST)/$(WORK)/src/butler_tagsview.o \
	$(P_HOST)/$(WORK)/src/butler_tagwidget.o \
	$(P_HOST)/$(WORK)/src/butler_waresmodel.o \
	$(P_HOST)/$(WORK)/src/butler_waresview.o \
	$(P_HOST)/$(WORK)/src/main.o \
	$(P_HOST)/$(WORK)/src/moc/butler_accountingview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_buyitemview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_custommodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_customview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_edititemview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_editshopview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_edittagview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_editwareview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_itemsmodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_mainview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_newitemview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_newshopview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_newtagview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_newwareview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_queryoptionsview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_shoppingview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_shoppingmodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_shopsmodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_shopsview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_stockmodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_stockview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_tagfilterview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_tagsmodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_tagsview.o \
	$(P_HOST)/$(WORK)/src/moc/butler_tagwidget.o \
	$(P_HOST)/$(WORK)/src/moc/butler_waresmodel.o \
	$(P_HOST)/$(WORK)/src/moc/butler_waresview.o

include make/license-freebin.minc

BUILD_DEPS+=    $(P_HOST)/$(PKGNAME)/$(TCROOT)/$(BIN_DESKTOP) \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/applications/$(PKGNAME).desktop \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/copyright \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/accounting.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/add.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/buy.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/custom.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/delete.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/edit.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/query.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/shop.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/shopping.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/stock.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/tag.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/trash.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/ware.png \
		$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/pixmaps/$(PKGNAME).png

BUILD_DBG_DEPS+= $(P_HOST)/$(PKGNAME)/$(TCROOT)/$(BIN_DESKTOP)

#
#	build
#

include make/default_targets.minc

$(P_HOST)/$(WORK)/src/moc/%.o: $(P_HOST)/$(WORK)/src/moc/%.cpp
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	g++ -c $(CFLAGS) $(DEFINES) $(INCLUDES) -o $@ $<
	$(TARGETFINISHED)

$(P_HOST)/$(WORK)/src/moc/%.cpp: src/%.h
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	moc -o $@ $<
	$(TARGETFINISHED)

$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(BIN_DESKTOP): \
		$(DESKTOP_OBJECTS)
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	@test -d $(dir $(P_HOST)/$(PKGNAME)-dbg/$(TCROOT)/$(PREFIX)/lib/debug/$(BIN_DESKTOP)) || \
		mkdir -p $(dir $(P_HOST)/$(PKGNAME)-dbg/$(TCROOT)/$(PREFIX)/lib/debug/$(BIN_DESKTOP))
	$(LINK)
	$(OBJCOPY) --only-keep-debug $@ \
		$(P_HOST)/$(PKGNAME)-dbg/$(TCROOT)/$(PREFIX)/lib/debug/$(BIN_DESKTOP)
	$(STRIP) --strip-debug $@
	$(TARGETFINISHED)

$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/%.png: \
		share/icons/%.png
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	cp $< $@
	$(TARGETFINISHED)

$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/pixmaps/$(PKGNAME).png: \
		share/icons/butler.png
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	cp $< $@
	$(TARGETFINISHED)

$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/$(PKGNAME)/icons/copyright: \
		share/icons/copyright
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	cp share/icons/copyright $@
	$(TARGETFINISHED)

$(P_HOST)/$(PKGNAME)/$(TCROOT)/$(PREFIX)/share/applications/$(PKGNAME).desktop:
	$(TARGETINFO)
	@test -d $(dir $@) || mkdir -p $(dir $@)
	@echo "[Desktop Entry]" > $@
	@echo "Name=ButlerQt $(APIVERSION)" >> $@
	@echo "Caption=Butler" >> $@
	@echo "GenericName=Butler - shopping list and home accounting" >> $@
	@echo "MimeType=application/butler" >> $@
	@echo "Exec=/usr/bin/$(PKGNAME)" >> $@
	@echo "Type=Application" >> $@
	@echo "Encoding=UTF-8" >> $@
	@echo "Version=$(VERSION)" >> $@
	@echo "Categories=Application;Office;Qt;User" >> $@
	@echo "Icon=$(PKGNAME)" >> $@
	@echo "X-Window-Icon=$(PKGNAME)" >> $@
	@echo "X-Window-Icon-Dimmed=$(PKGNAME)" >> $@
	@echo "X-Osso-Service=$(PKGNAME)" >> $@
	@echo "X-Osso-Type=application/x-executable" >> $@
	$(TARGETFINISHED)

#
#	source package
#

include make/license-closedsrc.minc

include make/sourcepkg.minc

source-copy: sourcepkg/$(PRJNAME)-$(VERSION)
	$(TARGETINFO)
	cp Makefile sourcepkg/$(PRJNAME)-$(VERSION)/
	cp -r src sourcepkg/$(PRJNAME)-$(VERSION)/
	cp -r share sourcepkg/$(PRJNAME)-$(VERSION)/
	cp -r make sourcepkg/$(PRJNAME)-$(VERSION)/
	$(TARGETFINISHED)

#
#	gentoo local only ebuild
#

GENTOO_CATEGORY=x11-apps

include make/gentoopkg.minc

#
#	debian package
#

DEBIAN_PACKAGES=debian/$(PKGNAME)_$(VERSION)_$(DEBIAN_ARCH).deb \
		debian/$(PKGNAME)-dbg_$(VERSION)_$(DEBIAN_ARCH).deb

DEBIAN_SECTION=user
include make/debianpkg.minc

