
source: \
	$(DIST_DIR)/src/datamodel/butler_item.cpp \
	$(DIST_DIR)/src/datamodel/butler_item_set.cpp \
	$(DIST_DIR)/src/datamodel/butler_query.cpp \
	$(DIST_DIR)/src/datamodel/butler_query_set.cpp \
	$(DIST_DIR)/src/datamodel/butler_shop.cpp \
	$(DIST_DIR)/src/datamodel/butler_shop_set.cpp \
	$(DIST_DIR)/src/datamodel/butler_tag.cpp \
	$(DIST_DIR)/src/datamodel/butler_tag_set.cpp \
	$(DIST_DIR)/src/datamodel/butler_ware.cpp \
	$(DIST_DIR)/src/datamodel/butler_ware_set.cpp \
	$(DIST_DIR)/src/datamodel/butler_item.h \
	$(DIST_DIR)/src/datamodel/butler_item_set.h \
	$(DIST_DIR)/src/datamodel/butler_query.h \
	$(DIST_DIR)/src/datamodel/butler_query_set.h \
	$(DIST_DIR)/src/datamodel/butler_shop.h \
	$(DIST_DIR)/src/datamodel/butler_shop_set.h \
	$(DIST_DIR)/src/datamodel/butler_tag.h \
	$(DIST_DIR)/src/datamodel/butler_tag_set.h \
	$(DIST_DIR)/src/datamodel/butler_ware.h \
	$(DIST_DIR)/src/datamodel/butler_ware_set.h \
	$(DIST_DIR)/src/datamodel/butler_db.h \
	$(DIST_DIR)/src/datamodel/butler_item_db.h \
	$(DIST_DIR)/src/datamodel/butler_query_db.h \
	$(DIST_DIR)/src/datamodel/butler_shop_db.h \
	$(DIST_DIR)/src/datamodel/butler_ware_db.h \
	$(DIST_DIR)/src/datamodel/butler_tag_db.h \
	$(DIST_DIR)/src/datamodel/butler_macros.h \
	$(DIST_DIR)/src/datamodel/test/dbifc.cpp \
	$(DIST_DIR)/src/datamodel/test/item.cpp \
	$(DIST_DIR)/src/datamodel/test/item_set.cpp \
	$(DIST_DIR)/src/datamodel/test/query.cpp \
	$(DIST_DIR)/src/datamodel/test/query_set.cpp \
	$(DIST_DIR)/src/datamodel/test/shop.cpp \
	$(DIST_DIR)/src/datamodel/test/shop_set.cpp \
	$(DIST_DIR)/src/datamodel/test/tag.cpp \
	$(DIST_DIR)/src/datamodel/test/tag_set.cpp \
	$(DIST_DIR)/src/datamodel/test/ware.cpp \
	$(DIST_DIR)/src/datamodel/test/ware_set.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlitedb.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_itembought.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_item.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_item_db.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_queries.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_queries_db.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_queryshops.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_querytags.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_querywares.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_schemaversion.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_shop.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_shop_db.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_sql.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_sqlquery.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_tag.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_tag_db.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_warecategories.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_ware.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_ware_db.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlite_waretags.cpp \
	$(DIST_DIR)/src/sqlite/butler_sqlitedb.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_itembought.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_item.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_item_db.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_queries.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_queries_db.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_queryshops.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_querytags.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_querywares.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_schemaversion.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_shop.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_shop_db.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_sql.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_sqlquery.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_tag.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_tag_db.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_warecategories.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_ware.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_ware_db.h \
	$(DIST_DIR)/src/sqlite/butler_sqlite_waretags.h \
	$(DIST_DIR)/src/sqlite/test/item.cpp \
	$(DIST_DIR)/src/sqlite/test/query.cpp \
	$(DIST_DIR)/src/sqlite/test/shop.cpp \
	$(DIST_DIR)/src/sqlite/test/tag.cpp \
	$(DIST_DIR)/src/sqlite/test/ware.cpp \
	$(DIST_DIR)/src/qt/butler_accountingview.cpp \
	$(DIST_DIR)/src/qt/butler_application.cpp \
	$(DIST_DIR)/src/qt/butler_buyitemview.cpp \
	$(DIST_DIR)/src/qt/butler_config.cpp \
	$(DIST_DIR)/src/qt/butler_custommodel.cpp \
	$(DIST_DIR)/src/qt/butler_customview.cpp \
	$(DIST_DIR)/src/qt/butler_edititemview.cpp \
	$(DIST_DIR)/src/qt/butler_editshopview.cpp \
	$(DIST_DIR)/src/qt/butler_edittagview.cpp \
	$(DIST_DIR)/src/qt/butler_editwareview.cpp \
	$(DIST_DIR)/src/qt/butler_itemsmodel.cpp \
	$(DIST_DIR)/src/qt/butler_localdb.cpp \
	$(DIST_DIR)/src/qt/butler_mainview.cpp \
	$(DIST_DIR)/src/qt/butler_newitemview.cpp \
	$(DIST_DIR)/src/qt/butler_newshopview.cpp \
	$(DIST_DIR)/src/qt/butler_newtagview.cpp \
	$(DIST_DIR)/src/qt/butler_newwareview.cpp \
	$(DIST_DIR)/src/qt/butler_queryoptionsview.cpp \
	$(DIST_DIR)/src/qt/butler_shoppingmodel.cpp \
	$(DIST_DIR)/src/qt/butler_shoppingview.cpp \
	$(DIST_DIR)/src/qt/butler_shopsmodel.cpp \
	$(DIST_DIR)/src/qt/butler_shopsview.cpp \
	$(DIST_DIR)/src/qt/butler_stockmodel.cpp \
	$(DIST_DIR)/src/qt/butler_stockview.cpp \
	$(DIST_DIR)/src/qt/butler_tagfilterview.cpp \
	$(DIST_DIR)/src/qt/butler_tagsmodel.cpp \
	$(DIST_DIR)/src/qt/butler_tagsview.cpp \
	$(DIST_DIR)/src/qt/butler_tagwidget.cpp \
	$(DIST_DIR)/src/qt/butler_waresmodel.cpp \
	$(DIST_DIR)/src/qt/butler_waresview.cpp \
	$(DIST_DIR)/src/qt/butler_accountingview.h \
	$(DIST_DIR)/src/qt/butler_application.h \
	$(DIST_DIR)/src/qt/butler_buyitemview.h \
	$(DIST_DIR)/src/qt/butler_config.h \
	$(DIST_DIR)/src/qt/butler_custommodel.h \
	$(DIST_DIR)/src/qt/butler_customview.h \
	$(DIST_DIR)/src/qt/butler_edititemview.h \
	$(DIST_DIR)/src/qt/butler_editshopview.h \
	$(DIST_DIR)/src/qt/butler_edittagview.h \
	$(DIST_DIR)/src/qt/butler_editwareview.h \
	$(DIST_DIR)/src/qt/butler_itemsmodel.h \
	$(DIST_DIR)/src/qt/butler_localdb.h \
	$(DIST_DIR)/src/qt/butler_mainview.h \
	$(DIST_DIR)/src/qt/butler_newitemview.h \
	$(DIST_DIR)/src/qt/butler_newshopview.h \
	$(DIST_DIR)/src/qt/butler_newtagview.h \
	$(DIST_DIR)/src/qt/butler_newwareview.h \
	$(DIST_DIR)/src/qt/butler_queryoptionsview.h \
	$(DIST_DIR)/src/qt/butler_shoppingmodel.h \
	$(DIST_DIR)/src/qt/butler_shoppingview.h \
	$(DIST_DIR)/src/qt/butler_shopsmodel.h \
	$(DIST_DIR)/src/qt/butler_shopsview.h \
	$(DIST_DIR)/src/qt/butler_stockmodel.h \
	$(DIST_DIR)/src/qt/butler_stockview.h \
	$(DIST_DIR)/src/qt/butler_tagfilterview.h \
	$(DIST_DIR)/src/qt/butler_tagsmodel.h \
	$(DIST_DIR)/src/qt/butler_tagsview.h \
	$(DIST_DIR)/src/qt/butler_tagwidget.h \
	$(DIST_DIR)/src/qt/butler_waresmodel.h \
	$(DIST_DIR)/src/qt/butler_waresview.h \
	$(DIST_DIR)/src/qt/main.cpp \
	$(DIST_DIR)/share/icons/copyright \
	$(DIST_DIR)/share/icons/accounting.png \
	$(DIST_DIR)/share/icons/add.png \
	$(DIST_DIR)/share/icons/buy.png \
	$(DIST_DIR)/share/icons/custom.png \
	$(DIST_DIR)/share/icons/delete.png \
	$(DIST_DIR)/share/icons/edit.png \
	$(DIST_DIR)/share/icons/query.png \
	$(DIST_DIR)/share/icons/shop.png \
	$(DIST_DIR)/share/icons/shopping.png \
	$(DIST_DIR)/share/icons/stock.png \
	$(DIST_DIR)/share/icons/tag.png \
	$(DIST_DIR)/share/icons/trash.png \
	$(DIST_DIR)/share/icons/ware.png \
	$(DIST_DIR)/share/icons/butler.png

$(DIST_DIR)/%: %
	@test -d $(dir $@) || mkdir -p $(dir $@)
	cp -pd $< $@

