.\" Process this file with
.\" groff -man -Tascii man-file-name
.\" For help: http://www.schweikhardt.net/man_page_howto.html
.TH butler 1 "2009-2023" butler "User Manuals"

.SH NAME
butler \- Butler - shopping list and home accounting.

.SH SYNOPSIS
.B butler
.RS
.B [--dbfile|-d
.I sqlite-database-file
.B ] [--logDir|-l
.I log-directory
.B ] [--verbose|-v]
.br
.B [--help|-h]

.SH DESCRIPTION
 Butler is a shopping list like basic home accounting tool.

.SH OPTIONS
.IP "--dbfile|-d sqlite-database-file"
Use the given file as database.
.IP "--logDir|-l log-directory"
Use the given directory for logging. With no
.I log-directory
specified, there will be no logging.
.IP "--verbose|-v"
Write log messages to stderr as well, not only into log file.
.IP "--help|-h"
Short reminder of available options.

.SH AUTHOR
Császár Péter <csjpeter@gmail.com>
