name: Build Debian Package

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ "master", "stable", "release/*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-debian-package:
    name: Build Debian Package for Ubuntu 24.04
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debhelper-compat \
          cmake \
          pkg-config \
          qtbase5-dev \
          qtbase5-dev-tools \
          libqt5sql5-sqlite \
          libsqlite3-dev \
          dpkg-dev \
          build-essential

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc -b

    - name: List generated packages
      run: |
        ls -lh ../*.deb ../*.ddeb 2>/dev/null || true
        mkdir -p packages
        mv ../*.deb packages/ 2>/dev/null || true
        mv ../*.ddeb packages/ 2>/dev/null || true
        ls -lh packages/

    - name: Get package version
      id: get_version
      run: |
        if [ -n "${{ github.ref_name }}" ] && [[ "${{ github.ref_name }}" == v* ]]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION=$(dpkg-parsechangelog -S Version)
        fi
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Package version: ${VERSION}"

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          packages/*.deb
          packages/*.ddeb
        name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts (for non-tag builds)
      if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      uses: actions/upload-artifact@v4
      with:
        name: debian-packages-ubuntu-24.04
        path: |
          packages/*.deb
          packages/*.ddeb
        retention-days: 30
